# Generated by Django 3.0.4 on 2020-04-27 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('generation', models.CharField(blank=True, max_length=64, null=True)),
                ('cpu_nb', models.IntegerField()),
                ('cpu_speed', models.FloatField()),
                ('cores_nb', models.IntegerField()),
                ('threads_nb', models.IntegerField()),
                ('gpu_speed', models.FloatField()),
                ('gpu_nb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('fqdn_hostname', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('rack', models.CharField(max_length=64)),
                ('rack_position', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Cluster')),
                ('groups', models.ManyToManyField(to='manager.Group')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.HardwareSettings')),
            ],
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.Group')),
                ('hostname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.Host')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='host_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.HostStatus'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.HostType'),
        ),
        migrations.AddField(
            model_name='host',
            name='services',
            field=models.ManyToManyField(to='manager.Service'),
        ),
        migrations.CreateModel(
            name='DatacenterRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Datacenter')),
            ],
            options={
                'unique_together': {('center', 'name')},
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Environment'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.DatacenterRoom'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=50)),
                ('ref_address', models.CharField(max_length=64, unique=True)),
                ('mac_address', models.CharField(max_length=64, unique=True)),
                ('interface', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Host')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('fqdn_hostname', 'cluster'), ('hostname', 'cluster')},
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_type', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('interface', models.CharField(max_length=64)),
                ('raid_level', models.IntegerField()),
                ('volume_size', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Host')),
            ],
            options={
                'unique_together': {('server', 'disk_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together={('room', 'name', 'environment')},
        ),
    ]
