# Generated by Django 3.0.4 on 2020-04-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnvType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Cluster')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('fqdn_hostname', models.CharField(max_length=128)),
                ('rack', models.CharField(max_length=64)),
                ('rack_position', models.PositiveSmallIntegerField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Cluster')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Group')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cpu', models.CharField(max_length=64)),
                ('memory', models.PositiveIntegerField()),
                ('u_size', models.PositiveSmallIntegerField(default=1)),
                ('end_support', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Group')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='host',
            name='host_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.HostStatus'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.HostType'),
        ),
        migrations.AddField(
            model_name='host',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Server'),
        ),
        migrations.AddField(
            model_name='host',
            name='service',
            field=models.ManyToManyField(to='manager.Service'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.EnvType'),
        ),
    ]
