# Generated by Django 3.0.4 on 2020-04-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('cpu_nb', models.IntegerField()),
                ('cpu_speed', models.FloatField()),
                ('cores_nb', models.IntegerField()),
                ('threads_nb', models.IntegerField()),
                ('gpu_speed', models.FloatField()),
                ('gpu_nb', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='cores_nb',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cpu_nb',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cpu_speed',
        ),
        migrations.RemoveField(
            model_name='host',
            name='gpu_nb',
        ),
        migrations.RemoveField(
            model_name='host',
            name='gpu_speed',
        ),
        migrations.RemoveField(
            model_name='host',
            name='threads_nb',
        ),
    ]
