# Generated by Django 3.0.4 on 2020-04-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_env_type_host_status_host_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Env_type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Cluster')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128)),
                ('fqdn_hostname', models.CharField(max_length=128)),
                ('rack', models.CharField(max_length=64)),
                ('rack_position', models.IntegerField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Cluster')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Group')),
                ('host_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host_status')),
                ('host_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host_type')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=256)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Group')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
