# Generated by Django 3.0.4 on 2020-04-13 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_cluster_group_host_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('cpu', models.CharField(max_length=64)),
                ('memory', models.PositiveIntegerField()),
                ('u_size', models.PositiveSmallIntegerField(default=1)),
                ('end_support', models.DateField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='cluster',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Env_type'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host_status'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host_type'),
        ),
        migrations.AlterField(
            model_name='host',
            name='rack_position',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='host',
            name='server',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.Server'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='service',
            field=models.ManyToManyField(to='manager.Service'),
        ),
    ]
