# Generated by Django 3.0.4 on 2020-04-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200413_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Env_type'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host_status'),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Host_type'),
        ),
    ]
