# Generated by Django 3.0.4 on 2020-04-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200413_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='env_type',
            new_name='EnvType',
        ),
        migrations.RenameModel(
            old_name='host_status',
            new_name='HostStatus',
        ),
        migrations.RenameModel(
            old_name='host_type',
            new_name='HostType',
        ),
    ]
